CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'projections') THEN
CREATE SCHEMA projections;
END IF;
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.budget_category_limits (
                                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                    "BudgetId" text NOT NULL,
                                                    "CategoryId" text NOT NULL,
                                                    "Limit" numeric NOT NULL,
                                                    CONSTRAINT "PK_budget_category_limits" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.budgets (
                                     "Id" text NOT NULL,
                                     "UserId" text NOT NULL,
                                     "Month" integer NOT NULL,
                                     "Year" integer NOT NULL,
                                     "TotalLimit" numeric NOT NULL,
                                     "Currency" text NOT NULL,
                                     "Recurring" boolean NOT NULL,
                                     "CreatedAt" timestamp with time zone NOT NULL,
                                     "UpdatedAt" timestamp with time zone,
                                     CONSTRAINT "PK_budgets" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.checkpoints (
                                         "Id" text NOT NULL,
                                         "Position" numeric(20,0) NOT NULL,
                                         "UpdatedAt" timestamp with time zone NOT NULL,
                                         CONSTRAINT "PK_checkpoints" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.credit_card_accounts (
                                                  "Id" text NOT NULL,
                                                  "UserId" text NOT NULL,
                                                  "Name" text NOT NULL,
                                                  "Currency" character varying(16) NOT NULL,
                                                  "SettlementAccountId" text NOT NULL,
                                                  "BankProvider" character varying(32) NOT NULL,
                                                  "ProductCode" character varying(64) NOT NULL,
                                                  "CreditLimit" numeric(18,2) NOT NULL,
                                                  "StatementClosingDay" integer NOT NULL,
                                                  "GracePeriodDays" integer NOT NULL,
                                                  "UnbilledBalance" numeric(18,2) NOT NULL,
                                                  "ActiveStatementBalance" numeric(18,2),
                                                  "ActiveStatementOutstandingBalance" numeric(18,2),
                                                  "ActiveStatementMinimumPaymentDue" numeric(18,2),
                                                  "ActiveStatementDueDate" date,
                                                  "ActiveStatementPeriodCloseDate" date,
                                                  "Color" text,
                                                  "LastFourDigits" text,
                                                  "IsActive" boolean NOT NULL,
                                                  "CreatedAt" timestamp with time zone NOT NULL,
                                                  "UpdatedAt" timestamp with time zone,
                                                  CONSTRAINT "PK_credit_card_accounts" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.credit_card_statements (
                                                    "Id" text NOT NULL,
                                                    "CreditCardAccountId" text NOT NULL,
                                                    "PeriodFrom" date NOT NULL,
                                                    "PeriodTo" date NOT NULL,
                                                    "StatementDate" date NOT NULL,
                                                    "DueDate" date NOT NULL,
                                                    "StatementBalance" numeric(18,2) NOT NULL,
                                                    "OutstandingBalance" numeric(18,2) NOT NULL,
                                                    "MinimumPaymentDue" numeric(18,2) NOT NULL,
                                                    "PolicyCode" character varying(64) NOT NULL,
                                                    "PolicyVersion" character varying(32) NOT NULL,
                                                    "CreatedAt" timestamp with time zone NOT NULL,
                                                    "UpdatedAt" timestamp with time zone,
                                                    CONSTRAINT "PK_credit_card_statements" PRIMARY KEY ("CreditCardAccountId", "Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.expenses (
                                      "Id" text NOT NULL,
                                      "UserId" text NOT NULL,
                                      "AccountId" text NOT NULL,
                                      "CategoryId" text NOT NULL,
                                      "SubcategoryId" text,
                                      "Amount" numeric NOT NULL,
                                      "Currency" text NOT NULL,
                                      "Date" date NOT NULL,
                                      "Description" text NOT NULL,
                                      "Recurring" boolean NOT NULL,
                                      "MetadataJson" text,
                                      "IsDeleted" boolean NOT NULL,
                                      "CreatedAt" timestamp with time zone NOT NULL,
                                      "UpdatedAt" timestamp with time zone,
                                      CONSTRAINT "PK_expenses" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.funding_accounts (
                                              "Id" text NOT NULL,
                                              "UserId" text NOT NULL,
                                              "Name" text NOT NULL,
                                              "Kind" character varying(32) NOT NULL,
                                              "Currency" character varying(16) NOT NULL,
                                              "Balance" numeric(18,2) NOT NULL,
                                              "Color" text,
                                              "IsActive" boolean NOT NULL,
                                              "CreatedAt" timestamp with time zone NOT NULL,
                                              "UpdatedAt" timestamp with time zone,
                                              CONSTRAINT "PK_funding_accounts" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.monthly_stats (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "UserId" text NOT NULL,
                                           "Year" integer NOT NULL,
                                           "Month" integer NOT NULL,
                                           "TotalSpent" numeric NOT NULL,
                                           "Currency" text NOT NULL,
                                           CONSTRAINT "PK_monthly_stats" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.processed_messages (
                                                "MessageId" uuid NOT NULL,
                                                "ProcessedAt" timestamp with time zone NOT NULL,
                                                CONSTRAINT "PK_processed_messages" PRIMARY KEY ("MessageId")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE TABLE projections.spending_summaries (
                                                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                "UserId" text NOT NULL,
                                                "Month" integer NOT NULL,
                                                "Year" integer NOT NULL,
                                                "CategoryId" text NOT NULL,
                                                "CategoryName" text NOT NULL,
                                                "TotalSpent" numeric NOT NULL,
                                                CONSTRAINT "PK_spending_summaries" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_budget_category_limits_BudgetId" ON projections.budget_category_limits ("BudgetId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE UNIQUE INDEX "IX_budget_category_limits_BudgetId_CategoryId" ON projections.budget_category_limits ("BudgetId", "CategoryId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE UNIQUE INDEX "IX_budgets_UserId_Month_Year" ON projections.budgets ("UserId", "Month", "Year");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_credit_card_accounts_SettlementAccountId" ON projections.credit_card_accounts ("SettlementAccountId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_credit_card_accounts_UserId" ON projections.credit_card_accounts ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_credit_card_statements_CreditCardAccountId" ON projections.credit_card_statements ("CreditCardAccountId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_expenses_AccountId" ON projections.expenses ("AccountId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_expenses_CategoryId" ON projections.expenses ("CategoryId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_expenses_Date" ON projections.expenses ("Date");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_expenses_UserId" ON projections.expenses ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_funding_accounts_UserId" ON projections.funding_accounts ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_monthly_stats_UserId_Year" ON projections.monthly_stats ("UserId", "Year");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE UNIQUE INDEX "IX_monthly_stats_UserId_Year_Month" ON projections.monthly_stats ("UserId", "Year", "Month");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE INDEX "IX_spending_summaries_UserId_Month_Year" ON projections.spending_summaries ("UserId", "Month", "Year");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
CREATE UNIQUE INDEX "IX_spending_summaries_UserId_Month_Year_CategoryId" ON projections.spending_summaries ("UserId", "Month", "Year", "CategoryId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423223146_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260423223146_Initial', '10.0.7');
END IF;
END $EF$;
COMMIT;

