CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'projections') THEN
CREATE SCHEMA projections;
END IF;
END $EF$;

CREATE TABLE projections.accounts (
                                      "Id" text NOT NULL,
                                      "UserId" text NOT NULL,
                                      "Name" text NOT NULL,
                                      "Type" text NOT NULL,
                                      "Currency" text NOT NULL,
                                      "Balance" numeric NOT NULL,
                                      "CreditLimit" numeric,
                                      "BillingCycleDay" integer,
                                      "CurrentDebt" numeric,
                                      "LinkedBankAccountId" text,
                                      "Color" text,
                                      "LastFourDigits" text,
                                      "IsActive" boolean NOT NULL,
                                      "CreatedAt" timestamp with time zone NOT NULL,
                                      "UpdatedAt" timestamp with time zone,
                                      CONSTRAINT "PK_accounts" PRIMARY KEY ("Id")
);

CREATE TABLE projections.budget_category_limits (
                                                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                    "BudgetId" text NOT NULL,
                                                    "CategoryId" text NOT NULL,
                                                    "Limit" numeric NOT NULL,
                                                    CONSTRAINT "PK_budget_category_limits" PRIMARY KEY ("Id")
);

CREATE TABLE projections.budgets (
                                     "Id" text NOT NULL,
                                     "UserId" text NOT NULL,
                                     "Month" integer NOT NULL,
                                     "Year" integer NOT NULL,
                                     "TotalLimit" numeric NOT NULL,
                                     "Currency" text NOT NULL,
                                     "Recurring" boolean NOT NULL,
                                     "CreatedAt" timestamp with time zone NOT NULL,
                                     "UpdatedAt" timestamp with time zone,
                                     CONSTRAINT "PK_budgets" PRIMARY KEY ("Id")
);

CREATE TABLE projections.checkpoints (
                                         "Id" text NOT NULL,
                                         "Position" numeric(20,0) NOT NULL,
                                         "UpdatedAt" timestamp with time zone NOT NULL,
                                         CONSTRAINT "PK_checkpoints" PRIMARY KEY ("Id")
);

CREATE TABLE projections.expenses (
                                      "Id" text NOT NULL,
                                      "UserId" text NOT NULL,
                                      "AccountId" text NOT NULL,
                                      "CategoryId" text NOT NULL,
                                      "SubcategoryId" text,
                                      "Amount" numeric NOT NULL,
                                      "Currency" text NOT NULL,
                                      "Date" date NOT NULL,
                                      "Description" text NOT NULL,
                                      "Recurring" boolean NOT NULL,
                                      "MetadataJson" text,
                                      "IsDeleted" boolean NOT NULL,
                                      "CreatedAt" timestamp with time zone NOT NULL,
                                      "UpdatedAt" timestamp with time zone,
                                      CONSTRAINT "PK_expenses" PRIMARY KEY ("Id")
);

CREATE TABLE projections.monthly_stats (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "UserId" text NOT NULL,
                                           "Year" integer NOT NULL,
                                           "Month" integer NOT NULL,
                                           "TotalSpent" numeric NOT NULL,
                                           "Currency" text NOT NULL,
                                           CONSTRAINT "PK_monthly_stats" PRIMARY KEY ("Id")
);

CREATE TABLE projections.spending_summaries (
                                                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                                "UserId" text NOT NULL,
                                                "Month" integer NOT NULL,
                                                "Year" integer NOT NULL,
                                                "CategoryId" text NOT NULL,
                                                "CategoryName" text NOT NULL,
                                                "TotalSpent" numeric NOT NULL,
                                                CONSTRAINT "PK_spending_summaries" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_accounts_UserId" ON projections.accounts ("UserId");

CREATE INDEX "IX_budget_category_limits_BudgetId" ON projections.budget_category_limits ("BudgetId");

CREATE UNIQUE INDEX "IX_budgets_UserId_Month_Year" ON projections.budgets ("UserId", "Month", "Year");

CREATE INDEX "IX_expenses_AccountId" ON projections.expenses ("AccountId");

CREATE INDEX "IX_expenses_CategoryId" ON projections.expenses ("CategoryId");

CREATE INDEX "IX_expenses_Date" ON projections.expenses ("Date");

CREATE INDEX "IX_expenses_UserId" ON projections.expenses ("UserId");

CREATE INDEX "IX_monthly_stats_UserId_Year" ON projections.monthly_stats ("UserId", "Year");

CREATE INDEX "IX_spending_summaries_UserId_Month_Year" ON projections.spending_summaries ("UserId", "Month", "Year");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260406173620_Initial', '10.0.5');

COMMIT;

